### ISSUE TITLE
Unable to install on Manjaro Linux (Arch)

### ISSUE THREAD

**Issue by jc00ke** [aptible/omnibus-aptible-toolbelt#44]
```
> sudo mkdir -p /opt/aptible-toolbelt
> sudo chown -R "$USER" /opt/aptible-toolbelt
> bundle
> bundle exec omnibus build aptible-toolbelt
```
[Console output](https://gist.github.com/jc00ke/5b1717546e15b9e370d14c9925d856d8)

This was on Ruby 2.5.1. Maybe the versions of `libresolve` et al, are too old, or too new?

**Comment by krallin** [comment]
These libraries are [normally considered safe by Omnibus](https://github.com/chef/omnibus/blob/879913aad6748816046857caf50069e68fb31cef/lib/omnibus/whitelist.rb#L17-L33), but they're [explicitly not included on Arch](https://github.com/chef/omnibus/blob/879913aad6748816046857caf50069e68fb31cef/lib/omnibus/whitelist.rb#L35-L47).

Unfortunately, I'm not familiar enough with Arch to say why that might be the case.

That said, if your only goal is to be able to run the CLI on Arch, note that when the health check fails, the CLI's technically already built.. All there is left to do is to create a symlink from `/usr/local/bin/aptible` to `/opt/aptible-toolbelt/bin/aptible`

**Comment by jc00ke** [comment]
Thanks @krallin
